# Generated by Django 5.2.14 on 2026-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoround',
            name='draw_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
